// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: reason-proto/reason.proto

package reason

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_INTERNAL          ErrorReason = 0
	ErrorReason_TOO_MANY_REQUESTS ErrorReason = 1
	ErrorReason_ILLEGAL_PARAMETER ErrorReason = 2
	ErrorReason_NOT_FOUND         ErrorReason = 3
	ErrorReason_UNAUTHORIZED      ErrorReason = 4
	ErrorReason_FORBIDDEN         ErrorReason = 5
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "INTERNAL",
		1: "TOO_MANY_REQUESTS",
		2: "ILLEGAL_PARAMETER",
		3: "NOT_FOUND",
		4: "UNAUTHORIZED",
		5: "FORBIDDEN",
	}
	ErrorReason_value = map[string]int32{
		"INTERNAL":          0,
		"TOO_MANY_REQUESTS": 1,
		"ILLEGAL_PARAMETER": 2,
		"NOT_FOUND":         3,
		"UNAUTHORIZED":      4,
		"FORBIDDEN":         5,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_reason_proto_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_reason_proto_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_reason_proto_reason_proto_rawDescGZIP(), []int{0}
}

var File_reason_proto_reason_proto protoreflect.FileDescriptor

const file_reason_proto_reason_proto_rawDesc = "" +
	"\n" +
	"\x19reason-proto/reason.proto\x12\treason.v1\x1a\x13errors/errors.proto*\x9d\x01\n" +
	"\vErrorReason\x12\x12\n" +
	"\bINTERNAL\x10\x00\x1a\x04\xa8E\xf4\x03\x12\x1b\n" +
	"\x11TOO_MANY_REQUESTS\x10\x01\x1a\x04\xa8E\xad\x03\x12\x1b\n" +
	"\x11ILLEGAL_PARAMETER\x10\x02\x1a\x04\xa8E\x90\x03\x12\x13\n" +
	"\tNOT_FOUND\x10\x03\x1a\x04\xa8E\x90\x03\x12\x16\n" +
	"\fUNAUTHORIZED\x10\x04\x1a\x04\xa8E\x91\x03\x12\x13\n" +
	"\tFORBIDDEN\x10\x05\x1a\x04\xa8E\x93\x03B0\n" +
	"\treason.v1P\x01Z\x13./api/reason;reason\xa2\x02\vAPIReasonV1b\x06proto3"

var (
	file_reason_proto_reason_proto_rawDescOnce sync.Once
	file_reason_proto_reason_proto_rawDescData []byte
)

func file_reason_proto_reason_proto_rawDescGZIP() []byte {
	file_reason_proto_reason_proto_rawDescOnce.Do(func() {
		file_reason_proto_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reason_proto_reason_proto_rawDesc), len(file_reason_proto_reason_proto_rawDesc)))
	})
	return file_reason_proto_reason_proto_rawDescData
}

var file_reason_proto_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_reason_proto_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: reason.v1.ErrorReason
}
var file_reason_proto_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reason_proto_reason_proto_init() }
func file_reason_proto_reason_proto_init() {
	if File_reason_proto_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reason_proto_reason_proto_rawDesc), len(file_reason_proto_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reason_proto_reason_proto_goTypes,
		DependencyIndexes: file_reason_proto_reason_proto_depIdxs,
		EnumInfos:         file_reason_proto_reason_proto_enumTypes,
	}.Build()
	File_reason_proto_reason_proto = out.File
	file_reason_proto_reason_proto_goTypes = nil
	file_reason_proto_reason_proto_depIdxs = nil
}
