// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"auth/internal/biz"
	"auth/internal/conf"
	"auth/internal/data"
	"auth/internal/server"
	"auth/internal/service"
	"github.com/go-kratos/kratos/v2"
)

import (
	_ "github.com/go-cinch/common/plugins/kratos/encoding/yml"
	_ "github.com/go-cinch/common/proto/params"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
)

// Injectors from wire.go:

// wireApp initializes the Kratos application.
func wireApp(bootstrap *conf.Bootstrap) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	authRepo := data.NewAuthRepo(dataData)
	transaction := data.NewTransaction(dataData)
	universalClient, err := data.NewRedis(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cache := data.NewCache(bootstrap, universalClient)
	authUseCase := biz.NewAuthUseCase(bootstrap, authRepo, transaction, cache)
	userRepo := data.NewUserRepo(dataData)
	hotspotRepo := data.NewHotspotRepo(dataData)
	userUseCase := biz.NewUserUseCase(bootstrap, userRepo, hotspotRepo, transaction, cache)
	roleRepo := data.NewRoleRepo(dataData)
	roleUseCase := biz.NewRoleUseCase(bootstrap, roleRepo, transaction, cache)
	permissionRepo := data.NewPermissionRepo(dataData)
	permissionUseCase := biz.NewPermissionUseCase(bootstrap, permissionRepo)
	actionRepo := data.NewActionRepo(dataData)
	actionUseCase := biz.NewActionUseCase(bootstrap, actionRepo, transaction, cache)
	userGroupRepo := data.NewUserGroupRepo(dataData)
	userGroupUseCase := biz.NewUserGroupUseCase(bootstrap, userGroupRepo, transaction, cache)
	whitelistRepo := data.NewWhitelistRepo(dataData)
	whitelistUseCase := biz.NewWhitelistUseCase(bootstrap, whitelistRepo, transaction, cache)
	healthRepo := data.NewHealthRepo(dataData, universalClient)
	authService := service.NewAuthService(bootstrap, authUseCase, userUseCase, roleUseCase, permissionUseCase, actionUseCase, userGroupUseCase, whitelistUseCase, hotspotRepo, healthRepo)
	grpcServer := server.NewGRPCServer(bootstrap, authService, universalClient)
	httpServer := server.NewHTTPServer(bootstrap, authService, universalClient, whitelistUseCase)
	app := newApp(grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
