// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"auth/internal/biz"
	"auth/internal/conf"
	"auth/internal/data"
	"auth/internal/server"
	"auth/internal/service"
	"auth/internal/task"
	"github.com/go-kratos/kratos/v2"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(c *conf.Bootstrap) (*kratos.App, func(), error) {
	universalClient, err := data.NewRedis(c)
	if err != nil {
		return nil, nil, err
	}
	db, err := data.NewDB(c)
	if err != nil {
		return nil, nil, err
	}
	sonyflake, err := data.NewSonyflake(c)
	if err != nil {
		return nil, nil, err
	}
	tracerProvider, err := data.NewTracer(c)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup := data.NewData(universalClient, db, sonyflake, tracerProvider)
	actionRepo := data.NewActionRepo(dataData)
	userRepo := data.NewUserRepo(dataData, actionRepo)
	transaction := data.NewTransaction(dataData)
	cache := data.NewCache(universalClient)
	userUseCase := biz.NewUserUseCase(c, userRepo, transaction, cache)
	taskTask, err := task.NewTask(c, userUseCase)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	actionUseCase := biz.NewActionUseCase(c, actionRepo, transaction, cache)
	roleRepo := data.NewRoleRepo(dataData, actionRepo)
	roleUseCase := biz.NewRoleUseCase(c, roleRepo, transaction, cache)
	userGroupRepo := data.NewUserGroupRepo(dataData, actionRepo, userRepo)
	userGroupUseCase := biz.NewUserGroupUseCase(c, userGroupRepo, transaction, cache)
	authService := service.NewAuthService(taskTask, userUseCase, actionUseCase, roleUseCase, userGroupUseCase)
	grpcServer := server.NewGRPCServer(c, authService)
	httpServer := server.NewHTTPServer(c, authService)
	app := newApp(grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
