-- +migrate Up
-- SQL in section 'Up' is executed when this migration is applied
CREATE TABLE role
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   CHARACTER VARYING(50) NULL,
    word   CHARACTER VARYING(50) NULL,
    action TEXT NULL
);

COMMENT ON COLUMN role.id IS 'auto increment id';
COMMENT ON COLUMN role.name IS 'name';
COMMENT ON COLUMN role.word IS 'keyword, must be unique, used as frontend display';
COMMENT ON COLUMN role.action IS 'role permission/action code array';

CREATE UNIQUE INDEX idx_role_word ON role (word);

-- +migrate Down
DROP TABLE role;

