-- +migrate Up
-- SQL in section 'Up' is executed when this migration is applied
CREATE TABLE "t_user"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(3) WITHOUT TIME ZONE NULL,
    updated_at  TIMESTAMP(3) WITHOUT TIME ZONE NULL,
    role_id     BIGINT NULL,
    action      TEXT NULL,
    username    CHARACTER VARYING(191) NULL,
    code        CHARACTER(8) NOT NULL,
    password    TEXT NULL,
    platform    CHARACTER VARYING(50) NULL,
    last_login  TIMESTAMP(3) WITHOUT TIME ZONE NULL,
    locked      SMALLINT DEFAULT 0 NULL,
    lock_expire BIGINT NULL,
    wrong       BIGINT NULL
);

COMMENT ON COLUMN "t_user".id IS 'auto increment id';
COMMENT ON COLUMN "t_user".created_at IS 'create time';
COMMENT ON COLUMN "t_user".updated_at IS 'update time';
COMMENT ON COLUMN "t_user".role_id IS 'role id';
COMMENT ON COLUMN "t_user".action IS 'permission/action code array';
COMMENT ON COLUMN "t_user".username IS 'user login name';
COMMENT ON COLUMN "t_user".code IS 'user code';
COMMENT ON COLUMN "t_user".password IS 'password';
COMMENT ON COLUMN "t_user".platform IS 'device platform: pc/android/ios/mini...';
COMMENT ON COLUMN "t_user".last_login IS 'last login time';
COMMENT ON COLUMN "t_user".locked IS 'locked(0: unlock, 1: locked)';
COMMENT ON COLUMN "t_user".lock_expire IS 'lock expiration time';
COMMENT ON COLUMN "t_user".wrong IS 'wrong password count';

CREATE UNIQUE INDEX idx_user_username ON "t_user" (username);
CREATE UNIQUE INDEX idx_user_code ON "t_user" (code);
CREATE INDEX idx_user_role_id ON "t_user" (role_id);

-- +migrate Down
DROP TABLE "t_user";

