-- +migrate Up
-- SQL in section 'Up' is executed when this migration is applied
CREATE TABLE t_action
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     CHARACTER VARYING(50) NULL,
    code     CHARACTER(8) NOT NULL,
    word     CHARACTER VARYING(50) NULL,
    resource TEXT NULL,
    menu     TEXT NULL,
    btn      TEXT NULL
);

COMMENT ON COLUMN t_action.id IS 'auto increment id';
COMMENT ON COLUMN t_action.name IS 'name';
COMMENT ON COLUMN t_action.code IS 'code';
COMMENT ON COLUMN t_action.word IS 'keyword, must be unique, used as frontend display';
COMMENT ON COLUMN t_action.resource IS 'resource rules, split by newline; examples: GET|/user, PUT|/role/*';
COMMENT ON COLUMN t_action.menu IS 'menu list, split by newline';
COMMENT ON COLUMN t_action.btn IS 'button list, split by newline';

CREATE UNIQUE INDEX idx_action_word ON t_action (word);
CREATE UNIQUE INDEX idx_action_code ON t_action (code);

-- +migrate Down
DROP TABLE t_action;

