-- +migrate Up
-- SQL in section 'Up' is executed when this migration is applied
CREATE TABLE user_group
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   CHARACTER VARYING(50) NULL,
    word   CHARACTER VARYING(50) NULL,
    action TEXT NULL
);

COMMENT ON COLUMN user_group.id IS 'auto increment id';
COMMENT ON COLUMN user_group.name IS 'name';
COMMENT ON COLUMN user_group.word IS 'keyword, must be unique, used as frontend display';
COMMENT ON COLUMN user_group.action IS 'user group permission/action code array';

CREATE UNIQUE INDEX idx_user_group_word ON user_group (word);

CREATE TABLE user_user_group_relation
(
    user_id       BIGINT NOT NULL,
    user_group_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, user_group_id)
);

COMMENT ON COLUMN user_user_group_relation.user_id IS 'user id';
COMMENT ON COLUMN user_user_group_relation.user_group_id IS 'user group id';

CREATE INDEX idx_user_user_group_relation_user_group_id ON user_user_group_relation (user_group_id);

-- +migrate Down
DROP TABLE user_user_group_relation;
DROP TABLE user_group;

