-- +migrate Up
CREATE TABLE whitelist
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category SMALLINT NOT NULL,
    resource TEXT NOT NULL
);

COMMENT ON COLUMN whitelist.id IS 'auto increment id';
COMMENT ON COLUMN whitelist.category IS 'category(0:permission, 1:jwt)';
COMMENT ON COLUMN whitelist.resource IS 'resource rules, split by newline';

CREATE INDEX idx_whitelist_category ON whitelist (category);

-- +migrate Down
DROP TABLE whitelist;

