server:
  machineId: ''
  http:
    addr: 0.0.0.0:6060
    timeout: 20s
    # service path prefix, check permission will use it
    path: '/auth'
  grpc:
    addr: 0.0.0.0:6160
    timeout: 20s
  language: 'en'
  jwt: true
  permission:
    enable: true
    # use nginx auth_request set direct=false
    # direct means call api directly not through /permission
    direct: false
    # nginx auth_request request_method: `GET` request_uri: `/api/auth/game`, action resource: `GET|/auth/game`, so prefix is `/api`
    prefix: '/api'
  idempotent: true
  validate: true
  # disable biz.Cache or not
  nocache: false
  logLevel: 'info'
data:
  database:
    driver: mysql
    # dsn: 'root:root@tcp(127.0.0.1:3306)/auth?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
    dsn: ''
    endpoint: '127.0.0.1:3306'
    username: 'root'
    password: 'root'
    schema: 'auth'
    query: 'charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
  #    tenants:
  #      auth.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/auth?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms}'
  #      auth2.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/auth2?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
  #      auth3.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/auth3?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
  #      auth4.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/auth4?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
  redis:
    # redis dsn like this:
    # redis://[:password@]host[:port][/dbnumber]
    # redis://[:password@]host1[:port][,host2:[:port]][,hostN:[:port]][?master=masterName&sentinel=true]
    dsn: 'redis://127.0.0.1:6379/0'
tracer:
  enable: true
  otlp:
    # how to run a otel-collector? see this: https://github.com/SigNoz/signoz/blob/develop/deploy/README.md#using-docker-compose
    endpoint: ''
    insecure: true
  stdout:
    prettyPrint: false
auth:
  jwt:
    key: 'auth'
    expires: '24h'
