server:
  machineId: ''
  http:
    addr: 0.0.0.0:6060
    timeout: 20s
  grpc:
    addr: 0.0.0.0:6160
    timeout: 20s
  language: 'en'
  jwt:
    # enable jwt, default use jwtV4 and HS512 algorithm, see: https://github.com/go-cinch/common/blob/jwt/v1.0.3/jwt/jwt.go#L123
    enable: true
    key: 'auth'
    expires: '24h'
  permission: true
  idempotent: true
  validate: true
  # disable biz.Cache or not
  nocache: false
  logLevel: 'info'
data:
  database:
    driver: mysql
    # dsn: 'root:root@tcp(127.0.0.1:3306)/auth?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
    dsn: ''
    endpoint: '127.0.0.1:3306'
    username: 'root'
    password: 'root'
    schema: 'auth'
    query: 'charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
  #    tenants:
  #      auth.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/auth?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms}'
  #      auth2.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/auth2?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
  #      auth3.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/auth3?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
  #      auth4.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/auth4?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
  redis:
    # redis dsn like this:
    # redis://[:password@]host[:port][/dbnumber]
    # redis://[:password@]host1[:port][,host2:[:port]][,hostN:[:port]][?master=masterName&sentinel=true]
    dsn: 'redis://127.0.0.1:6379/0'
tracer:
  enable: true
  otlp:
    # how to run a otel-collector? see: https://github.com/SigNoz/signoz/blob/develop/deploy/README.md#using-docker-compose
    endpoint: ''
    insecure: true
  stdout:
    prettyPrint: false
