server:
  machineId: ''
  http:
    addr: 0.0.0.0:6060
    timeout: 20s
  grpc:
    addr: 0.0.0.0:6160
    timeout: 20s
data:
  database:
    driver: mysql
    dsn: '${DATA_DATABASE_DSN:root:root@tcp(127.0.0.1:3306)/test?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms}'
  redis:
    # redis dsn like this:
    # redis://[:password@]host[:port][/dbnumber]
    # redis-socket://[:password@]path[?db=dbnumber]
    # redis-sentinel://[:password@]host1[:port][,host2:[:port]][,hostN:[:port]][?master=masterName]
    dsn: '${DATA_REDIS_DSN:redis://127.0.0.1:6379/0}'
tracer:
  enable: false
  otlp:
    # how to run a otel-collector? see this: https://github.com/SigNoz/signoz/blob/develop/deploy/README.md#using-docker-compose
    endpoint: '${TRACER_OTLP_ENDPOINT:127.0.0.1:4317}'
    insecure: true
  stdout:
    prettyPrint: false
tasks:
  - category: task1
    uuid: id1
    expr: '0/1 * * * ?'
  - category: task2
    uuid: id2
    expr: '0/5 * * * ?'
auth:
  jwt:
    key: 'auth'
    expires: '24h'