server:
  machineId: ''
  http:
    addr: 0.0.0.0:6060
    timeout: 20s
  grpc:
    addr: 0.0.0.0:6160
    timeout: 20s
  language: 'en'
data:
  database:
    driver: mysql
    dsn: '${DATA_DATABASE_DSN:root:root@tcp(127.0.0.1:3306)/test?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms}'
  redis:
    # redis dsn like this:
    # redis://[:password@]host[:port][/dbnumber]
    # redis://[:password@]host1[:port][,host2:[:port]][,hostN:[:port]][?master=masterName&sentinel=true]
    dsn: '${DATA_REDIS_DSN:redis://127.0.0.1:6379/0}'
tracer:
  enable: false
  otlp:
    # how to run a otel-collector? see this: https://github.com/SigNoz/signoz/blob/develop/deploy/README.md#using-docker-compose
    endpoint: '${TRACER_OTLP_ENDPOINT:127.0.0.1:4317}'
    insecure: true
  stdout:
    prettyPrint: false
auth:
  jwt:
    key: 'auth'
    expires: '24h'