// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAction = "t_action"

// Action mapped from table <t_action>
type Action struct {
	ID       int64   `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:auto increment id" json:"id,string"`                                                      // auto increment id
	Name     *string `gorm:"column:name;type:character varying(50);comment:name" json:"name"`                                                                                     // name
	Code     string  `gorm:"column:code;type:character(8);not null;uniqueIndex:idx_action_code,priority:1;comment:code" json:"code"`                                              // code
	Word     *string `gorm:"column:word;type:character varying(50);uniqueIndex:idx_action_word,priority:1;comment:keyword, must be unique, used as frontend display" json:"word"` // keyword, must be unique, used as frontend display
	Resource *string `gorm:"column:resource;type:text;comment:resource rules, split by newline; examples: GET|/user, PUT|/role/*" json:"resource"`                                // resource rules, split by newline; examples: GET|/user, PUT|/role/*
	Menu     *string `gorm:"column:menu;type:text;comment:menu list, split by newline" json:"menu"`                                                                               // menu list, split by newline
	Btn      *string `gorm:"column:btn;type:text;comment:button list, split by newline" json:"btn"`                                                                               // button list, split by newline
}

// TableName Action's table name
func (*Action) TableName() string {
	return TableNameAction
}
