// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAction = "action"

// Action mapped from table <action>
type Action struct {
	ID       uint64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:auto increment id" json:"id,string"`
	Name     string `gorm:"column:name;comment:name" json:"name"`
	Code     string `gorm:"column:code;not null;comment:code" json:"code"`
	Word     string `gorm:"column:word;comment:keyword, must be unique, used as frontend display" json:"word"`
	Resource string `gorm:"column:resource;comment:resource array, split by break line str, example: GET|/user+\n+PUT,PATCH|/role/*+\n+GET|/action" json:"resource"`
	Menu     string `gorm:"column:menu;comment:menu array, split by break line str" json:"menu"`
	Btn      string `gorm:"column:btn;comment:btn array, split by break line str" json:"btn"`
}

// TableName Action's table name
func (*Action) TableName() string {
	return TableNameAction
}
