// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRole = "role"

// Role mapped from table <role>
type Role struct {
	ID     uint64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:auto increment id" json:"id,string"`
	Name   string `gorm:"column:name;comment:name" json:"name"`
	Word   string `gorm:"column:word;comment:keyword, must be unique, used as frontend display" json:"word"`
	Action string `gorm:"column:action;comment:role action code array" json:"action"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
