// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRole = "role"

// Role mapped from table <role>
type Role struct {
	ID     int64   `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:auto increment id" json:"id,string"`                                                    // auto increment id
	Name   *string `gorm:"column:name;type:character varying(50);comment:name" json:"name"`                                                                                   // name
	Word   *string `gorm:"column:word;type:character varying(50);uniqueIndex:idx_role_word,priority:1;comment:keyword, must be unique, used as frontend display" json:"word"` // keyword, must be unique, used as frontend display
	Action *string `gorm:"column:action;type:text;comment:role permission/action code array" json:"action"`                                                                   // role permission/action code array
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
