// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserGroup = "user_group"

// UserGroup mapped from table <user_group>
type UserGroup struct {
	ID     uint64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:auto increment id" json:"id,string"`
	Name   string `gorm:"column:name;comment:name" json:"name"`
	Word   string `gorm:"column:word;comment:keyword, must be unique, used as frontend display" json:"word"`
	Action string `gorm:"column:action;comment:user group action code array" json:"action"`
	Users  []User `gorm:"many2many:user_user_group_relation" json:"users"`
}

// TableName UserGroup's table name
func (*UserGroup) TableName() string {
	return TableNameUserGroup
}
