// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/golang-module/carbon/v2"
)

const TableNameUser = "t_user"

// User mapped from table <t_user>
type User struct {
	ID         int64            `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:auto increment id" json:"id,string"`                               // auto increment id
	CreatedAt  *carbon.DateTime `gorm:"column:created_at;type:timestamp(3) without time zone;comment:create time" json:"created_at"`                                  // create time
	UpdatedAt  *carbon.DateTime `gorm:"column:updated_at;type:timestamp(3) without time zone;comment:update time" json:"updated_at"`                                  // update time
	RoleID     *int64           `gorm:"column:role_id;type:bigint;index:idx_user_role_id,priority:1;comment:role id" json:"role_id,string"`                           // role id
	Action     *string          `gorm:"column:action;type:text;comment:permission/action code array" json:"action"`                                                   // permission/action code array
	Username   *string          `gorm:"column:username;type:character varying(191);uniqueIndex:idx_user_username,priority:1;comment:user login name" json:"username"` // user login name
	Code       string           `gorm:"column:code;type:character(8);not null;uniqueIndex:idx_user_code,priority:1;comment:user code" json:"code"`                    // user code
	Password   *string          `gorm:"column:password;type:text;comment:password" json:"password"`                                                                   // password
	Platform   *string          `gorm:"column:platform;type:character varying(50);comment:device platform: pc/android/ios/mini..." json:"platform"`                   // device platform: pc/android/ios/mini...
	LastLogin  *carbon.DateTime `gorm:"column:last_login;type:timestamp(3) without time zone;comment:last login time" json:"last_login"`                              // last login time
	Locked     *int16           `gorm:"column:locked;type:smallint;comment:locked(0: unlock, 1: locked)" json:"locked"`                                               // locked(0: unlock, 1: locked)
	LockExpire *int64           `gorm:"column:lock_expire;type:bigint;comment:lock expiration time" json:"lock_expire,string"`                                        // lock expiration time
	Wrong      *int64           `gorm:"column:wrong;type:bigint;comment:wrong password count" json:"wrong,string"`                                                    // wrong password count
	Role       *Role            `gorm:"foreignKey:RoleID" json:"role"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
