// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserUserGroupRelation = "user_user_group_relation"

// UserUserGroupRelation mapped from table <user_user_group_relation>
type UserUserGroupRelation struct {
	UserID      int64 `gorm:"column:user_id;type:bigint;primaryKey;comment:user id" json:"user_id"`                                                                               // user id
	UserGroupID int64 `gorm:"column:user_group_id;type:bigint;primaryKey;index:idx_user_user_group_relation_user_group_id,priority:1;comment:user group id" json:"user_group_id"` // user group id
}

// TableName UserUserGroupRelation's table name
func (*UserUserGroupRelation) TableName() string {
	return TableNameUserUserGroupRelation
}
