// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWhitelist = "whitelist"

// Whitelist mapped from table <whitelist>
type Whitelist struct {
	ID       int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:auto increment id" json:"id,string"`                                       // auto increment id
	Category int16  `gorm:"column:category;type:smallint;not null;index:idx_whitelist_category,priority:1;comment:category(0:permission, 1:jwt)" json:"category"` // category(0:permission, 1:jwt)
	Resource string `gorm:"column:resource;type:text;not null;comment:resource rules, split by newline" json:"resource"`                                          // resource rules, split by newline
}

// TableName Whitelist's table name
func (*Whitelist) TableName() string {
	return TableNameWhitelist
}
