// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWhitelist = "whitelist"

// Whitelist mapped from table <whitelist>
type Whitelist struct {
	ID       uint64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:auto increment id" json:"id,string"`           // auto increment id
	Category uint32 `gorm:"column:category;not null;comment:category(0:permission, 1:jwt, 2:idempotent)" json:"category"` // category(0:permission, 1:jwt, 2:idempotent)
	/*
		resource array, split by break line str, example: GET|/user+
		+PUT,PATCH|/role/*+
		+GET|/action
	*/
	Resource string `gorm:"column:resource;not null;comment:resource array, split by break line str, example: GET|/user+\n+PUT,PATCH|/role/*+\n+GET|/action" json:"resource"`
}

// TableName Whitelist's table name
func (*Whitelist) TableName() string {
	return TableNameWhitelist
}
